### ISSUE TITLE
sometimes "mmt start fails because of kafka

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#205]
ERROR Illegal State: failed to start kafka, check log file for more details: /home/ubuntu/ModernMT/runtime/newb1/logs/embedded-kafka.log

**Comment by cattoni** [comment]
Sometimes issuing "mmt start" fails with the message:

`ERROR` Illegal State: failed to start kafka, check log file for more details: /home/ubuntu/ModernMT/runtime/newb1/logs/embedded-kafka.log`


The only way I have found to make it start is to remove the directory

`$MMT_HOME/engines/ENGINE/model/kafka`

which appears quite rude.

**Comment by nicolabertoldi** [comment]
I also experienced this issu, often when a code recompilation occurred.
and I solved in the same way, i.e. removing the kafka directory

**Comment by cattoni** [comment]
@davidecaroselli are some of the kafka data currently in

`$MMT_HOME/engines/ENGINE/models/kafka`

better positioned into a correspending runtime dir?

**Comment by davidecaroselli** [comment]
I've also noticed that problem, I'm currently investigating but I found a quick and dirty solution that it's a little safer than remove everything: just remove the folder **karka/zdata**

**Comment by cattoni** [comment]
ok, thanks.
So it appears something related to zookeeper info/status.

**Comment by mehmedes** [comment]
I tried deleting the folder. I no longer get the error message but MMT doesn't manage to load the model. I've tried installing MMT binaries and installing from source. None of the installation options had an effect. MMT freezes when trying to load a model:

File "./mmt", line 589, in <module>
    main()
  File "./mmt", line 567, in main
    actions[command](args)
  File "./mmt", line 224, in main_start
    node.wait('JOINED')
  File "/home/mttranslation429/ModernMT/cli/cluster.py", line 471, in wait
    time.sleep(1

**Comment by davidecaroselli** [comment]
Hi @mehmedes 

have you deleted the folder **kafka/zdata** or **kafka**?
If you deleted the whole **kafka** folder, you have basically deleted part of the models so it's possible that the system hangs. In the case of @cattoni the models inside Kafka were empty, so the system could safely recover from it.

**Comment by mehmedes** [comment]
Both didn't work. I first deleted zdata, then kafka.
When using the binaries installation it gets stuck when loading models.
When using source installation it freezes starting MMT engine

**Comment by davidecaroselli** [comment]
could you upload the file `runtime/default/logs/node.log` when the system gets stuck? So I can have a look if there is some log that shows the problem. Thanks.

**Comment by davidecaroselli** [comment]
@mehmedes sorry, could you please upload the whole `runtime/default/logs` folder please?

**Comment by mehmedes** [comment]
[logs.zip](https://github.com/ModernMT/MMT/files/634561/logs.zip)

**Comment by mehmedes** [comment]
This is the log for the binaries Installation

**Comment by mehmedes** [comment]
This is the log for the source installation 
[logs.zip](https://github.com/ModernMT/MMT/files/634565/logs.zip)

**Comment by davidecaroselli** [comment]
Hi @mehmedes 
Looking at the logs I spotted multiple problems.

**Binary Installation**
- MMT uses also ports **2181** and **9092** that are hardcoded at the moment, this means that you cannot have multiple instances of MMT running on the same machine. The engine failed to connect to port *2181*, maybe it's a firewall problem, or the process is running without enough privileges, it strongly depends on your machine settings.
- Unfortunately you're hitting a known bug for MMT at the moment: issue #195. If it's possible for your use-case, you should split the large TM in more small, user-based TMs; MMT does not works very well with large generic TMs

**From-source installation**
- You have the same first issue of the *binary installation*
- It seems also that you have not built correctly MMT, maybe you missed one of the steps described here, or some of them failed? [Installing from source](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source-for-contributors)

**Comment by mehmedes** [comment]
I've now resetted the server and installed MMT anew. There's only one Installation now but I still can't load models, I've also used a txt corpus instead of tmx. The firewall is off and I've also tested running create and start with sudo.
[archive.zip](https://github.com/ModernMT/MMT/files/635671/archive.zip)
When running the Setup.py, it said 

> Installing kafka-0.10.0.1.../usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

I was able to install the previous version on the very same server and it worked.

**Comment by davidecaroselli** [comment]
>Installing kafka-0.10.0.1.../usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

I just pushed a fix into master that should solve this problem, in order to apply it you can simply replace the file [setup.py](https://github.com/ModernMT/MMT/blob/2930100aad17d54723bda45e5a5aca860fce9b8b/setup.py). Thanks for pointed it out!

**Regarding Kafka**
Everything seems ok now: from the log I can see that Kafka has started correctly.

**Regarding models**
The problem with the TooLargeTM has been fixed, but there is still some problems that, unfortunately, does not show in the log. I'd say that we can proceed in two steps:

1. Try creating the example engine like shown in the [README.md](https://github.com/ModernMT/MMT/blob/master/README.md#create-an-engine) file and check if that engine could successfully load and run.
2. If first step succeed, are you able to pass me the training files and/or models of the broken engine? So that I can reproduce the problem myself and investigate the cause

**Comment by mehmedes** [comment]
I used Europarl English German from Opus. First I tried the TMX file. Then, I tried the txt files. In both cases training was completed, on the source as well as binary installation. 
I've now run a test using docker with the txt files. Again training was completed, but loading the model didn't work.

**Comment by mehmedes** [comment]
@davidecaroselli I've just sent you my engine via filetransfer. Looking forward to your feedback.

**Comment by davidecaroselli** [comment]
Hi @mehmedes thanks for the files. We will investigate asap.
Regarding issue #195 it can be possible, but you should see the error message in the logs, let's see!

**Comment by mehmedes** [comment]
@davidecaroselli When creating an engine with more than one parallel corpora or translation memory, MMT starts the engine and everything works well.

**Comment by davidecaroselli** [comment]
Good news!

This issue has been solved in commit afe53fae2258e55d8c2d59883b193025463654fe.
The problem was Zookeeper local data becoming corrupted after MMT crash; we solved this issue by replacing it at every `mmt start`.

**Comment by jgrivolla** [comment]
I'm still encountering the same problem sometimes with MMT 3.3.1 in Docker. Removing `runtime/default/kafka/` solved it apparently (at least for now).
