### ISSUE TITLE
XLIFF script

### ISSUE THREAD

**Issue by michaelstolzenberg** [ModernMT/MMT#343]
Hi,
I'm trying to translate multiple SDLXLIFF files using this script:
extras/translate_xliff
as suggested here:
https://github.com/ModernMT/MMT/issues/281

It seems to work fine at first but when looking at the translated files they are just copies of the original files so it hasn't translated anything.

The same thing happens when I try to translate a single file using:
sudo ./mmt translate --batch --xliff < /file/path/file.sdlxliff

I DO get a translation when entering single lines from the SDLXLIFF files into the command line:
sudo ./mmt translate "translate this line"

Why might this be?

**Comment by davidecaroselli** [comment]
Hi @michaelstolzenberg 

we have just pushed a fix in the `master` branch for XLIFF translation. Can you please check if that solves your issue?

Thank you!
Davide

**Comment by michaelstolzenberg** [comment]
Hi @davidecaroselli 

thanks for the quick reply. I pulled the latest version and the translation seems to work fine. But there is still an issue with the output:
-----------------------------
original trans-units:
-----------------------------
<trans-unit id="4aad91b1-c7e4-4d5e-bba9-4f6da5eaa147">
  <source>
    <g id="29">hello<g id="35"></g>world<g id="50"></g></g>
  </source>
  <seg-source>
    <g id="29">hello<g id="35"></g>world<g id="50"></g></g>
  </seg-source>
  <target/>
</trans-unit>

<trans-unit id="f1678a82-26b6-4047-a4ec-fb2703696d1a">
  <source>
    <g id="65">hello world</g>
  </source>
  <seg-source>
    <g id="65">hello world</g>
  </seg-source>
  <target/>
</trans-unit>
-----------------------------
expected translation output:
-----------------------------
<trans-unit id="4aad91b1-c7e4-4d5e-bba9-4f6da5eaa147">
  <source>
    <g id="29">hello<g id="35"></g>world<g id="50"></g></g>
  </source>
  <seg-source>
    <g id="29">hello<g id="35"></g>world<g id="50"></g></g>
  </seg-source>
  <target>
    <g id="29">ciao<g id="35"></g>mundo<g id="50"></g></g>
  </target>
</trans-unit>

<trans-unit id="f1678a82-26b6-4047-a4ec-fb2703696d1a">
  <source>
    <g id="65">hello world</g>
  </source>
  <seg-source>
    <g id="65">hello world</g>
  </seg-source>
  <target>
    <g id="65">ciao mundo</g>
  </target>
</trans-unit>
-----------------------------
actual translation output:
-----------------------------
<trans-unit id="4aad91b1-c7e4-4d5e-bba9-4f6da5eaa147">
  <source>
    <g id="29">hello<g id="35"></g>world<g id="50"></g></g>
  </source>
  <seg-source>
    <g id="29">hello<g id="35"></g>world<g id="50"></g></g>
  </seg-source>
  <target>
    <g id="29">ciao<g id="35"></g><g id="50"></g>&lt;/seg-sourcemundo</g>
  </target>
</trans-unit>

<trans-unit id="f1678a82-26b6-4047-a4ec-fb2703696d1a">
  <source>
    <g id="65">hello world</g>
  </source>
  <seg-source>
    <g id="65">hello world</g>
  </seg-source>
  <target>
    <g id="65">ciao mundo</g>&lt;/seg-source
  </target>
</trans-unit>

**Comment by davidecaroselli** [comment]
Ok, can you please check the ModernMT log? It's in `mmt/runtime/<engine-name>/logs/node.log`. You should look if the translation request was in fact something like "<g id="65">hello world</g>&lt;/seg-source".

I want to verify if it's a problem in the reading or in the writing.

Thanks!

**Comment by michaelstolzenberg** [comment]
line from node.log:
`2018-02-06 09:37:05,831 INFO  eu.modernmt.rest.RESTServer$Router [qtp672493939-188] "GET /translate?q=%3Cg+id%3D%2265%22%3Eciao+mundo%3C%2Fg%3E%3C%2Fseg-source&source=de&target=en&priority=background" 200 21318`

without URL tags:
`2018-02-06 09:37:05,831 INFO  eu.modernmt.rest.RESTServer$Router [qtp672493939-188] "GET /translate?q=<g id="65">ciao mundo</g></seg-source&source=de&target=en&priority=background" 200 21318`

**Comment by davidecaroselli** [comment]
Perfect, I will dig more!

**Comment by davidecaroselli** [comment]
Hi @michaelstolzenberg 

the fix in `master` branch an will be also release shortly with MMT 2.4.

Thanks for your support!
Davide
